name: ml
channels:
  - conda-forge
dependencies:
  - altair
  - archspec
  - asttokens
  - attrs
  - aws-c-auth
  - aws-c-cal
  - aws-c-common
  - aws-c-compression
  - aws-c-event-stream
  - aws-c-http
  - aws-c-io
  - aws-c-mqtt
  - aws-c-s3
  - aws-c-sdkutils
  - aws-checksums
  - aws-crt-cpp
  - aws-sdk-cpp
  - blinker
  - boltons
  - brotli
  - brotli-bin
  - brotli-python
  - bzip2
  - c-ares
  - ca-certificates
  - cachetools
  - cairo
  - certifi
  - cffi
  - chardet
  - charset-normalizer
  - click
  - cmcrameri
  - colorama
  - comm
  - conda
  - conda-libmamba-solver
  - conda-package-handling
  - conda-package-streaming
  - contourpy
  - cudatoolkit
  - cycler
  - datamol
  - debugpy
  - decorator
  - distro
  - exceptiongroup
  - executing
  - exmol
  - expat
  - fmt
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - freetype
  - freetype-py
  - frozendict
  - fsspec
  - gitdb
  - gitpython
  - greenlet
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - importlib_resources
  - intel-openmp
  - ipykernel
  - ipython
  - jedi
  - jinja2
  - jsonpatch
  - jsonpointer
  - jsonschema
  - jsonschema-specifications
  - jupyter_client
  - jupyter_core
  - khronos-opencl-icd-loader
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libabseil
  - libarchive
  - libarrow
  - libarrow-acero
  - libarrow-dataset
  - libarrow-substrait
  - libblas
  - libboost
  - libboost-python
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcrc32c
  - libcurl
  - libdeflate
  - libevent
  - libexpat
  - libffi
  - libglib
  - libgoogle-cloud
  - libgoogle-cloud-storage
  - libgrpc
  - libhwloc
  - libiconv
  - libintl
  - libjpeg-turbo
  - liblapack
  - libmamba
  - libmambapy
  - libparquet
  - libpng
  - libprotobuf
  - libre2-11
  - libsodium
  - libsolv
  - libsqlite
  - libssh2
  - libthrift
  - libtiff
  - libutf8proc
  - libwebp-base
  - libxcb
  - libxml2
  - libzlib
  - loguru
  - lz4-c
  - lzo
  - m2w64-gcc-libgfortran
  - m2w64-gcc-libs
  - m2w64-gcc-libs-core
  - m2w64-gmp
  - m2w64-libwinpthread-git
  - mamba
  - markupsafe
  - matminer
  - matplotlib-base
  - matplotlib-inline
  - medchem
  - menuinst
  - miniforge_console_shortcut
  - mkl
  - msys2-conda-epoch
  - munkres
  - narwhals
  - nest-asyncio
  - numpy
  - openjpeg
  - openmm
  - openssl
  - orc
  - packaging
  - pandas
  - parso
  - pcre2
  - pdbfixer
  - pickleshare
  - pillow
  - pip
  - pixman
  - pkgutil-resolve-name
  - platformdirs
  - pluggy
  - prompt-toolkit
  - protobuf>=4.0
  - psutil
  - pthread-stubs
  - pthreads-win32
  - pure_eval
  - pyarrow
  - pybind11-abi
  - pycairo
  - pycosat
  - pycparser
  - pydeck
  - pygments
  - pyparsing
  - pysocks
  - python=3.10
  - python-dateutil
  - python-tzdata
  - python_abi
  - pytz
  - pywin32
  - pyyaml
  - pyzmq
  - qhull
  - rdkit
  - re2
  - referencing
  - reportlab
  - reproc
  - reproc-cpp
  - requests
  - rlpycairo
  - rpds-py
  - ruamel.yaml
  - ruamel.yaml.clib
  - scikit-learn=1.6.1
  - scipy
  - selfies
  - setuptools
  - six
  - smmap
  - snappy
  - sqlalchemy
  - stack_data
  - streamlit
  - tbb
  - tenacity
  - threadpoolctl
  - tk
  - toml
  - tornado
  - tqdm
  - traitlets
  - truststore
  - typing-extensions
  - typing_extensions
  - tzdata
  - ucrt
  - unicodedata2
  - urllib3
  - vc
  - vc14_runtime
  - vs2015_runtime
  - watchdog
  - wcwidth
  - wheel
  - win32_setctime
  - win_inet_pton
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - yaml
  - yaml-cpp
  - zeromq
  - zipp
  - zlib
  - zstandard
  - zstd
  - pip:
    - Mako==1.3.10
    - Markdown==3.8
    - PyYAML==6.0.2
    - SMACT==3.1.0
    - Werkzeug==3.1.3
    - absl-py==2.2.2
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.12.9
    - aiosignal==1.3.2
    - alembic==1.15.2
    - asdfghjkl==0.1a4
    - ase==3.25.0
    - astunparse==1.6.3
    - async-timeout==5.0.1
    - backcall==0.2.0
    - backpack-for-pytorch==1.7.1
    - beautifulsoup4==4.14.2
    - biopython==1.85
    - Brotli==1.1.0
    - cattrs==25.1.1
    - cffi==1.17.1
    - chembl-webresource-client==0.10.9
    - cmcrameri==0.0.0
    - colorlog==6.9.0
    - conda-libmamba-solver==25.4.0
    - curvlinops-for-pytorch==2.0.1
    - deepchem==2.8.0
    - dill==0.4.0
    - easydict==1.13
    - einconv==0.1.0
    - einops==0.8.1
    - ema-pytorch==0.7.7
    - et_xmlfile==2.0.0
    - exmol==3.3.0
    - filelock==3.18.0
    - flatbuffers==25.2.10
    - frozenlist==1.6.2
    - future==1.0.0
    - gallery_dl==1.30.10
    - gast==0.6.0
    - google-auth==2.38.0
    - google-auth-oauthlib==1.2.1
    - google-pasta==0.2.0
    - gpytorch==1.14
    - grpcio==1.71.0
    - h2==4.2.0
    - h5py==3.13.0
    - huggingface-hub==0.30.2
    - imbalanced-learn==0.13.0
    - importlib_metadata==8.7.0
    - ipykernel==6.29.5
    - ipython==8.12.0
    - ipywidgets==8.1.7
    - jaxtyping==0.3.2
    - jupyterlab_widgets==3.0.15
    - keras==2.15.0
    - kornia==0.8.1
    - kornia_rs==0.1.9
    - laplace-torch==0.2.2.2
    - libclang==18.1.1
    - libmambapy==2.2.0
    - lightning==2.5.3
    - lightning-uq-box==0.2.0
    - lightning-utilities==0.15.2
    - linear-operator==0.6
    - lxml==5.4.0
    - matminer==0.9.2
    - medchem==2.0.5
    - ml-dtypes==0.3.2
    - mlchemad==1.5.2
    - molcomplib==1.1.2
    - molgraph==0.7.11
    - multidict==6.4.4
    - multiprocess==0.70.18
    - munkres==1.1.4
    - numpy==1.26.4
    - oauthlib==3.2.2
    - openpyxl==3.1.5
    - opt_einsum==3.4.0
    - optuna==4.2.1
    - pandarallel==1.6.5
    - pathos==0.3.4
    - patsy==1.0.1
    - pdbfixer==1.11.0
    - pip==25.1.1
    - pkgutil_resolve_name==1.3.10
    - pox==0.3.6
    - ppft==1.7.7
    - propcache==0.3.1
    - protobuf==4.25.8
    - pyasn1==0.6.1
    - pyasn1_modules==0.4.2
    - pybtex==0.24.0
    - PySocks==1.7.1
    - python3-discogs-client==2.8
    - pytorch-lightning==2.5.3
    - rdkit==2023.9.5
    - regex==2024.11.6
    - reportlab==4.4.1
    - requests-cache==1.2.1
    - requests-oauthlib==2.0.0
    - rlPyCairo==0.2.0
    - rsa==4.9
    - safetensors==0.5.3
    - scikit-posthocs==0.14.0
    - seaborn==0.13.2
    - sklearn-compat==0.1.3
    - soupsieve==2.8
    - statsmodels==0.14.5
    - streamlit==1.45.1
    - sympy==1.14.0
    - tensorboard==2.15.2
    - tensorboard-data-server==0.7.2
    - tensorflow==2.15.1
    - tensorflow-estimator==2.15.0
    - tensorflow-intel==2.15.1
    - tensorflow-io-gcs-filesystem==0.31.0
    - termcolor==3.1.0
    - timm==1.0.19
    - tokenizers==0.21.1
    - torch==2.8.0
    - torch-geometric==2.6.1
    - torchmetrics==1.8.1
    - torchseg==0.0.1a4
    - torchvision==0.23.0
    - transformers==4.51.2
    - typer-slim==0.16.0
    - typing_extensions==4.13.2
    - uncertainty-toolbox==0.1.1
    - unicodedata2==16.0.0
    - unfoldNd==0.2.3
    - url-normalize==2.2.1
    - wadler_lindig==0.1.7
    - widgetsnbextension==4.0.14
    - win_inet_pton==1.1.0
    - wordcloud==1.9.4
    - wrapt==1.14.1
    - xgboost==3.0.0
    - yarl==1.20.0